name: ksqlDB Unit Test
description: unit test ksqlDB schema with GitHub actions
inputs:
  file1:
    description: Path to input-file
    default: /github/workspace/unit_tests/V000001__initialize_order_events_stream_input.sql
  file2:
    description: Path to output-file
    default: /github/workspace/unit_tests/V000001__initialize_order_events_stream_output.sql
  sql-file:
    description: Path to output-file
    default: /github/workspace/unit_tests/V000001__initialize_order_events_stream.sql
runs:
  using: docker
  image: docker://confluentinc/ksqldb-cli:latest
  args:
    - sh
    - -c  
    - (ksql-test-runner --input-file ${{ inputs.file1 }} --sql-file ${{ inputs.sql-file }} --output-file  ${{ inputs.file2 }} | grep -i 'test failed'); exit $?