name: ksqlDB Migrations Apply
description: apply ksqlDB schema with GitHub actions
inputs:
  config:
    description: Path to config file
    default: /github/workspace/ksql-migrations.properties
runs:
  using: docker
  image: ubuntu
  args:
    - echo
    - "ent -- $ENTITY"
