name: Create file
on: 
  workflow_dispatch: 
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      entity:
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ksql
    steps:
      - uses: actions/checkout@v2
      - uses: franzbischoff/replace_envs@v1
        env: 
          CONFLUENT_KSQLDB_ENDPOINT: ${{ secrets.CONFLUENT_KSQLDB_ENDPOINT }}
          CONFLUENT_KSQLDB_API_KEY: ${{ secrets.CONFLUENT_KSQLDB_API_KEY }}
          CONFLUENT_KSQLDB_API_KEY2: ${{ secrets.CONFLUENT_KSQLDB_API_KEY2 }}
          CONFLUENT_KSQLDB_API_SECRET: ${{ secrets.CONFLUENT_KSQLDB_API_SECRET }}
        with:
          from_file: 'ksql-migrations.properties'
          to_file: 'ksql-migrations.properties'
          commit: 'false'
      - uses: ./.github/actions/ksqldb-create
      - uses: ./.github/actions/ksqldb-ls
