name: workflow
on:
  pull_request:
    branches: ${{ github.ref_name }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ksql
    steps:
      - uses: actions/checkout@v2
      - uses: franzbischoff/replace_envs@v1
        env: 
          CONFLUENT_KSQLDB_ENDPOINT: ${{ secrets.CONFLUENT_KSQLDB_ENDPOINT }}
          CONFLUENT_KSQLDB_API_KEY: ${{ secrets.CONFLUENT_KSQLDB_API_KEY }}
          CONFLUENT_KSQLDB_API_KEY2: ${{ secrets.CONFLUENT_KSQLDB_API_KEY2 }}
          CONFLUENT_KSQLDB_API_SECRET: ${{ secrets.CONFLUENT_KSQLDB_API_SECRET }}
        with:
          from_file: 'ksql-migrations.properties'
          to_file: 'ksql-migrations.properties'
          commit: 'false'
      #- uses: ./.github/actions/ksqldb-unit-test  
      - uses: ./.github/actions/ksqldb-unit-test2
      - uses: ./.github/actions/ksqldb-migrations-validate
      - uses: ./.github/actions/ksqldb-migrations-apply
