name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      entity:
        required: true
      use-emoji:
        type: boolean
        description: Include  emojis
      environment:
        type: environment

jobs:
  greet:
    runs-on: ubuntu-latest
    

    steps:
    - name: ACTIONS_ALLOW_UNSECURE_COMMANDS
      id: ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo 'ACTIONS_ALLOW_UNSECURE_COMMANDS=true' >> $GITHUB_ENV
    - name: Send greeting
      run: |
        echo "${{ github.event.inputs.entity }} ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} ${{ github.event.inputs.name }}"
        echo "::set-env name=ENTITY::${{ github.event.inputs.entity }}"
    - name: test
      run: |
        export FOO=bar
        echo "::set-env name=FOO::$FOO"
    - name: test2
      run: echo $ENTITU
    - name: test3
      run: ls -l
    - name: uses
      uses: ./.github/actions/ksql@master
      env:
        ENTITY: ${{env.ENTITY}}
        
    
